---
default: &DEFAULT
    server: '127.0.0.1'
    port: 9876
    TZ_LOCAL: 'UTC'
    TZ_SERVER: 'UTC'
    loglevel: 'INFO'
    logformat: '%(asctime)-15s %(levelname)-6s %(name)s: %(message)s'
    logfile: 'pymt_api.log'
    instrument_list: {
        EURUSD: 'EURUSD',
        EURGBP: 'EURGBP',
        DAX: 'GER30',}

Axi_MT4:
    <<: *DEFAULT
    server: '192.168.1.248'
    port: 9876
    TZ_SERVER: 'Europe/Tallinn'
    TZ_LOCAL: 'Europe/Budapest'
    instrument_list: {
        AUS200: 'AUS200',
        CN50: 'CN50',
        EU50: 'EU50',
        FRA40: 'FRA40',
        DAX: 'GER30',
        HK50: 'HK50',
        JPN225: 'JPN225',
        SGFREE: 'SGFREE',
        UK100: 'UK100',
        US30: 'US30',
        US500: 'US500',
        USTECH: 'USTECH',
        UKOIL: 'UKOIL',
        USOIL: 'USOIL',
        BCHUSD: 'BCHUSD',
        BTCUSD: 'BTCUSD',
        ETHUSD: 'ETHUSD',
        LTCUSD: 'LTCUSD',
        XRPUSD: 'XRPUSD',
        CAC40.fs: 'CAC40.fs',
        CHINA50.fs: 'CHINA50.fs',
        DAX30.fs: 'DAX30.fs',
        DJ30.fs: 'DJ30.fs',
        EUSTX50.fs: 'EUSTX50.fs',
        FT100.fs: 'FT100.fs',
        HSI.fs: 'HSI.fs',
        NAS100.fs: 'NAS100.fs',
        NK225.fs: 'NK225.fs',
        S&P.fs: 'S&P.fs',
        SPI200.fs: 'SPI200.fs',
        WTI.fs: 'WTI.fs',
        BRENT.fs: 'BRENT.fs',
        COCOA.fs: 'COCOA.fs',
        COFFEE.fs: 'COFFEE.fs',
        COPPER.fs: 'COPPER.fs',
        NATGAS.fs: 'NATGAS.fs',
        SOYBEAN.fs: 'SOYBEAN.fs',
        AUDUSD: 'AUDUSD',
        EURGBP: 'EURGBP',
        EURJPY: 'EURJPY',
        GBPJPY: 'GBPJPY',
        GBPUSD: 'GBPUSD',
        NZDUSD: 'NZDUSD',
        USDCAD: 'USDCAD',
        USDCHF: 'USDCHF',
        USDJPY: 'USDJPY',
        XAUUSD: 'XAUUSD',
        XAGUSD: 'XAGUSD',
        AUDCAD: 'AUDCAD',
        AUDCHF: 'AUDCHF',
        AUDJPY: 'AUDJPY',
        AUDNOK: 'AUDNOK',
        AUDNZD: 'AUDNZD',
        AUDPLN: 'AUDPLN',
        AUDSEK: 'AUDSEK',
        AUDSGD: 'AUDSGD',
        CADCHF: 'CADCHF',
        CADJPY: 'CADJPY',
        CADSGD: 'CADSGD',
        CHFJPY: 'CHFJPY',
        CHFSEK: 'CHFSEK',
        CHFSGD: 'CHFSGD',
        EURAUD: 'EURAUD',
        EURCAD: 'EURCAD',
        EURCHF: 'EURCHF',
        EURCZK: 'EURCZK',
        EURHUF: 'EURHUF',
        EURNOK: 'EURNOK',
        EURNZD: 'EURNZD',
        EURPLN: 'EURPLN',
        EURRON: 'EURRON',
        EURRUB: 'EURRUB',
        EURSEK: 'EURSEK',
        EURSGD: 'EURSGD',
        EURTRY: 'EURTRY',
        EURZAR: 'EURZAR',
        GBPAUD: 'GBPAUD',
        GBPCAD: 'GBPCAD',
        GBPCHF: 'GBPCHF',
        GBPCZK: 'GBPCZK',
        GBPHUF: 'GBPHUF',
        GBPMXN: 'GBPMXN',
        GBPNOK: 'GBPNOK',
        GBPNZD: 'GBPNZD',
        GBPPLN: 'GBPPLN',
        GBPSEK: 'GBPSEK',
        GBPSGD: 'GBPSGD',
        GBPTRY: 'GBPTRY',
        MXNJPY: 'MXNJPY',
        NOKJPY: 'NOKJPY',
        NOKSEK: 'NOKSEK',
        NZDCAD: 'NZDCAD',
        NZDCHF: 'NZDCHF',
        NZDJPY: 'NZDJPY',
        PLNHUF: 'PLNHUF',
        SGDJPY: 'SGDJPY',
        TRYJPY: 'TRYJPY',
        USDBRL: 'USDBRL',
        USDCNH: 'USDCNH',
        USDCZK: 'USDCZK',
        USDHUF: 'USDHUF',
        USDILS: 'USDILS',
        USDINR: 'USDINR',
        USDMXN: 'USDMXN',
        USDNOK: 'USDNOK',
        USDPLN: 'USDPLN',
        USDRON: 'USDRON',
        USDRUB: 'USDRUB',
        USDSEK: 'USDSEK',
        USDSGD: 'USDSGD',
        USDTHB: 'USDTHB',
        USDTRY: 'USDTRY',
        USDZAR: 'USDZAR',
        USDHKD: 'USDHKD',
        ZARJPY: 'ZARJPY',
        XAUAUD: 'XAUAUD',
        XAUCHF: 'XAUCHF',
        XAUEUR: 'XAUEUR',
        XAUGBP: 'XAUGBP',
        XPTUSD: 'XPTUSD',
        EURUSD: 'EURUSD',}
